# === Tilesets === #

[[tilesets]]
    name = 'sprites_dino'

    input  = 'res/dino.png'
    output = 'src/res/sprites_dino.c'

    tile_width  = 4
    tile_height = 4

    palette = 'res/palette.png'
    bpp = 4

    static = true

[[tilesets]]
    name = 'sprites'

    input  = 'res/sprites.png'
    output = 'src/res/sprites.c'

    tile_width  = 2
    tile_height = 2

    palette = 'res/palette.png'
    bpp = 4

    static = true

[[tilesets]]
    name = 'tileset'

    input  = 'res/tileset.png'
    output = 'src/res/tileset.c'

    tile_width  = 1
    tile_height = 1

    palette = 'res/palette.png'
    bpp = 4

    static = true

# === Files === #

[[files]]
    name = 'sound_good'

    input  = 'res/sounds/good.raw'
    output = 'src/res/sounds/good.c'

[[files]]
    name = 'sound_bad'

    input  = 'res/sounds/bad.raw'
    output = 'src/res/sounds/bad.c'
